### ISSUE TITLE
Investigate techniques to crawl more metadata from datasets

### ISSUE THREAD

**Issue by matprov** [crim-ca/stac-populator#10]
Currently only a small portion of CMIP5/CMIP6 controlled vocabulary (CV) is crawled. 

The goal of this task is to make sure attributes defined here are crawled and / or add more metadata : https://github.com/cedadev/stac-generator-example/blob/master/collection_descriptions/CMIP6.CMIP.CanDCS-U6.yaml#L34

See CMIP6's Data Reference Syntax (DRS) for properties to extract as well as the Controlled Vocabulary (CV).

See those CMIP6 Planetary Computer catalogs:
- https://radiantearth.github.io/stac-browser/#/external/planetarycomputer.microsoft.com/api/stac/v1/collections/cil-gdpcir-cc-by?.language=en
- https://radiantearth.github.io/stac-browser/#/external/planetarycomputer.microsoft.com/api/stac/v1/collections/nasa-nex-gddp-cmip6

**Comment by huard** [comment]
I think we now have all the CMIP6 attributes.
