### ISSUE TITLE
Consider using the actual warnings module in case this is import within another script

### ISSUE THREAD

**Issue by matprov** [crim-ca/stac-populator#3]
Consider using https://pypi.python.org/pypi/colorama made for this kind of functionality.

Consider having an input parameter for coloring stuff or not (with colorama, simply call init() or not) without need for if/else formatting in the code. It might be redundant or inconvenient to have the escape codes in output logs, which could themselves colorize or expect raw text.

Combined use of [INFO] and various colours seems inadequate.

https://github.com/crim-ca/stac-populator/blob/a578dd6f8ad0191de4f696d714e1237d7b11e693/collection_processor.py#L151-L154

**Comment by huard** [comment]
I think mentions of bcolors have all been removed.
