### ISSUE TITLE
Revert changes to repo permissions

### ISSUE THREAD

**Issue by dchandan** [crim-ca/stac-populator#39]
@fmigneault can you revert changes to repo permissions that you have made recently? I was able to push to master directly for small error changes before but now I have to go through the whole PR process.

**Comment by fmigneault** [comment]
I am purposely limiting push to master to make sure we have some minimal review and that others are made aware of changes.
The only allowed push to master is to release a new version. 
You can make a PR and it will be merged right away if there is no impact.
