### ISSUE TITLE
Fix CLI runner

### ISSUE THREAD

**Issue by dchandan** [crim-ca/stac-populator#46]
Something is not working as expected with the CLI runner that @fmigneault put in place. The help text produced by running `stac-populator` should give a list of populations available, but right now it doesn't do that:

```
usage: stac-populator [-h] [--version] [--debug] {run} ...

STACpopulator operations.

options:
  -h, --help     show this help message and exit
  --version, -V  prints the version of the library and exits
  --debug        Set logger level to debug

command:
  STAC populator command to execute.

  {run}
    run          STACpopulator implementation runner.
```

**Comment by fmigneault** [comment]
You have to call `stac-populator run --help` to list implementations. 

`stac-populator --help` is to list available commands. For now, only `run` is defined, but we could have others to interact with STAC in different manners.

**Comment by dchandan** [comment]
Oh right! Silly me.
